# Generated by Django 4.0.5 on 2022-07-06 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('statement', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=1000)),
                ('output', models.CharField(max_length=1000)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problems')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5000)),
                ('verdict', models.CharField(max_length=50)),
                ('sub_time', models.DateTimeField(verbose_name='date submitted')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problems')),
            ],
        ),
    ]
